services:
############################# Elastic Search ###############################
  ElasticSearchService:
    image: elasticsearch:7.14.1
    container_name: ElasticSearchContainer
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - EKNetwork
    restart: always
############################# Kibana ###############################
  KibanaService:
    image: kibana:7.14.1
    container_name: KibanaContainer
    depends_on: ElasticSearchService
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://ElasticSearchContainer:9200/
    networks:
      - EKNetwork
    restart: always
networks:
  EKNetwork:
